//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wren.Emulation.MasterSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FieldNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FieldNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wren.Emulation.MasterSystem.Properties.FieldNames", typeof(FieldNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CycleCounter.
        /// </summary>
        public static string CpuData_CycleCounter {
            get {
                return ResourceManager.GetString("CpuData_CycleCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlagsRegister.
        /// </summary>
        public static string CpuData_FlagsRegister {
            get {
                return ResourceManager.GetString("CpuData_FlagsRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFF1.
        /// </summary>
        public static string CpuData_IFF1 {
            get {
                return ResourceManager.GetString("CpuData_IFF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFF2.
        /// </summary>
        public static string CpuData_IFF2 {
            get {
                return ResourceManager.GetString("CpuData_IFF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InteruptMode.
        /// </summary>
        public static string CpuData_InteruptMode {
            get {
                return ResourceManager.GetString("CpuData_InteruptMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InteruptRequested.
        /// </summary>
        public static string CpuData_InteruptRequested {
            get {
                return ResourceManager.GetString("CpuData_InteruptRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InteruptVectorRegister.
        /// </summary>
        public static string CpuData_InteruptVectorRegister {
            get {
                return ResourceManager.GetString("CpuData_InteruptVectorRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsHalted.
        /// </summary>
        public static string CpuData_IsHalted {
            get {
                return ResourceManager.GetString("CpuData_IsHalted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgramCounterRegister.
        /// </summary>
        public static string CpuData_ProgramCounterRegister {
            get {
                return ResourceManager.GetString("CpuData_ProgramCounterRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefreshRegister.
        /// </summary>
        public static string CpuData_RefreshRegister {
            get {
                return ResourceManager.GetString("CpuData_RefreshRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterA.
        /// </summary>
        public static string CpuData_RegisterA {
            get {
                return ResourceManager.GetString("CpuData_RegisterA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterAPrime.
        /// </summary>
        public static string CpuData_RegisterAPrime {
            get {
                return ResourceManager.GetString("CpuData_RegisterAPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterB.
        /// </summary>
        public static string CpuData_RegisterB {
            get {
                return ResourceManager.GetString("CpuData_RegisterB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterBPrime.
        /// </summary>
        public static string CpuData_RegisterBPrime {
            get {
                return ResourceManager.GetString("CpuData_RegisterBPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterC.
        /// </summary>
        public static string CpuData_RegisterC {
            get {
                return ResourceManager.GetString("CpuData_RegisterC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterCPrime.
        /// </summary>
        public static string CpuData_RegisterCPrime {
            get {
                return ResourceManager.GetString("CpuData_RegisterCPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterD.
        /// </summary>
        public static string CpuData_RegisterD {
            get {
                return ResourceManager.GetString("CpuData_RegisterD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterDPrime.
        /// </summary>
        public static string CpuData_RegisterDPrime {
            get {
                return ResourceManager.GetString("CpuData_RegisterDPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterE.
        /// </summary>
        public static string CpuData_RegisterE {
            get {
                return ResourceManager.GetString("CpuData_RegisterE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterEPrime.
        /// </summary>
        public static string CpuData_RegisterEPrime {
            get {
                return ResourceManager.GetString("CpuData_RegisterEPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterFPrime.
        /// </summary>
        public static string CpuData_RegisterFPrime {
            get {
                return ResourceManager.GetString("CpuData_RegisterFPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterH.
        /// </summary>
        public static string CpuData_RegisterH {
            get {
                return ResourceManager.GetString("CpuData_RegisterH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterHPrime.
        /// </summary>
        public static string CpuData_RegisterHPrime {
            get {
                return ResourceManager.GetString("CpuData_RegisterHPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterIX.
        /// </summary>
        public static string CpuData_RegisterIX {
            get {
                return ResourceManager.GetString("CpuData_RegisterIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterIY.
        /// </summary>
        public static string CpuData_RegisterIY {
            get {
                return ResourceManager.GetString("CpuData_RegisterIY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterL.
        /// </summary>
        public static string CpuData_RegisterL {
            get {
                return ResourceManager.GetString("CpuData_RegisterL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterLPrime.
        /// </summary>
        public static string CpuData_RegisterLPrime {
            get {
                return ResourceManager.GetString("CpuData_RegisterLPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StackPointerRegister.
        /// </summary>
        public static string CpuData_StackPointerRegister {
            get {
                return ResourceManager.GetString("CpuData_StackPointerRegister", resourceCulture);
            }
        }
    }
}
